# Site Info
title: Jacob Chen
tagline: 'Linux Developer'
description: ''
baseurl: ""
url: http://blog.iotwrt.com
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Jacob Chen
  description: Linux Developer.
  contact:
    github:    https://github.com/wzyy2
    email:     jacob-chen@iotwrt.com

# Navigation (2nd level links supported)
nav:
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# Puglins
mathjax: true # whether support mathjax
disqus_short_name: 'iotwrt' # leave blank if you don't want disqus

